on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - 'review_requested'
    paths:
      - 'contrib/**'

name: contrib

jobs:
  build-contrib:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add ghostscript imagemagick gnupg
            sed -i "s|<policy domain=\"coder\" rights=\"none\" pattern=\"PDF\" />|<policy domain=\"coder\" rights=\"read\|write\" pattern=\"PDF\" />|g" /etc/ImageMagick-*/policy.xml
            .github/ci/build_contrib.sh -halt-on-error -time -quiet -xelatex
        name: build test variants with XeLaTeX
      - uses: actions/upload-artifact@v2
        with:
          path: |
            build/*.pdf
        name: upload build artifacts