on:
  pull_request:
    types:
      - 'review_requested'
    paths:
      - 'contrib/**'

name: contrib

jobs:
  build-contrib:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: .github/ci/build_contrib.sh -halt-on-error -time -quiet -xelatex
        name: build test variants with XeLaTeX
      - run: cat build/build-*.log
        name: display build log
        if: ${{ failure() || success() }}
      - uses: actions/upload-artifact@v2
        with:
          path: |
            build/*.pdf
        name: upload build artifacts